### ISSUE TITLE
Esto no funciona

### ISSUE THREAD

**Issue by Leovor** [lozanoje/fvtt-module-CoC7-es#12]
Instale Babele y este modulo y todo esta igual en ingles como se usa esto?

**Comment by lozalojo** [comment]
Instale/Actualice sistema CoC de HavlockV
https://foundryvtt.com/packages/CoC7/

Instale/Actualice módulo Babele
https://foundryvtt.com/packages/babele/
Instale/Actualice módulo de la traducción Base:
https://foundryvtt.com/packages/FoundryVTT-ES/
Instale/Actualice módulo de la traducción de CoC:
https://foundryvtt.com/packages/call-of-cthulhu-7th-babele-es/

En Administración de módulos active Babele y las dos traducciones.
En Ajustes cambie el idioma a Español

Vuelva a escribir si tiene algún problema.

**Comment by Leovor** [comment]
Gracias por responder faltaba poner idioma español en ajustes del mundo,
todo funciona bien menos los ejemplos de actores cuando trato de abrir eso
sale el error Cannot read property "items" of null varias veces, aunque las
hojas de esbirro, villano y criatura se abren con el error que mencione, la
de personaje de los 1920 no abre ninguna hoja solo da el error. Ademas si
creo un actor aparece sin habilidades.

**Comment by lozalojo** [comment]
Es que no las puede abrir, son de solo lectura, debe importarlas (botón derecho), creará una entrada en la pestaña de personajes y podrá editarlo.
