### ISSUE TITLE
Enlace a fvtt-module-CoC7-es está caído

### ISSUE THREAD

**Issue by tristobal** [lozanoje/fvtt-module-CoC7-es#34]
En el archivo README.md el enlace a https://foundryvtt.com/packages/fvtt-module-CoC7-es/ está caido.
Debiese ser https://foundryvtt.com/packages/call-of-cthulhu-7th-babele-es ¿No?

**Comment by lozanoje** [comment]
Solucionado, se me olvidó actualizar el nombre del repo en el backend de foundryvtt

¡gracias por avisar, @tristobal !
