### ISSUE TITLE
Sugerencia

### ISSUE THREAD

**Issue by LoboEstelar** [lozanoje/fvtt-module-CoC7-es#35]
Muchas gracias por tú (o vuestro) esfuerzo. El trabajo es muy bueno y os lo agradezco. No obstante, ¿Podríais considerar incluir la descripción de algunas habilidades, solo las más problemáticas como Medicina, primeros auxilios, psicología, etc.? Sería bueno tenerlo ahí a mano para los jugadores.

De otra manera, si hay alguna forma de que colabore contigo, dímelo e intentaré ayudarte para mejorar esta excelente traducción.

**Comment by lozanoje** [comment]
Desafortunadamente, no es posible, todo ese material está sujeto a derechos de copyright propiedad de Edge Studio, de modo que no puedo incluirlo en ningún módulo de distribución libre.
